### ISSUE TITLE
EU Login Mobile 1.11.1 - Technical information

### ISSUE THREAD

**Issue by Hflores1982** [Hflores1982/Hackerone#3]
REMARK: This information should only be sent to European Commission Helpdesks or the developer of the app.

-------------------Additional information-------------------
Please provide any further information about the problem here.
------------------------------------------------------------
* Device information:
Device model: TINNO - U626AA
Android version: REL 12 - API 31

* EU Login Mobile app information:
EU Login Mobile version: 1.11.1
EU Login Mobile built for: release (prd)
EU Login base: https://ecas.ec.europa.eu/cas
Enrolment status: NO_ENROLMENT_STARTED
Registered device name: null
Unique device identifier: null
FCM ID: fXv7OTlRTUSuNO-2G1sL0m:APA91bGZW8hkYNfFZxV9buIvqaVT3HUM1pAS0ES9d7r2e4C61qzuj7yhSmPI8l08XlGu5XHlMRYXw7lWwMzBae1FfqQR0xh4iuZ_0DgV7Nve0Pt1yYupSqbNdcE99Kp2c6OTcyfoFX87
UID: null
Username: null
Are notifications enabled: Yes

* Biometric information:
Biometric enrolment status: NOT_STARTED
Biometric, pattern or pin set on device: Yes
Biometric hardware available: Yes
Is eligible for Biometric enrolment: No
Is eligible for Biometric authentication: No

* Permissions: 
	- android.permission.INTERNET
	- android.permission.ACCESS_NETWORK_STATE
	- android.permission.USE_FINGERPRINT
	- android.permission.USE_BIOMETRIC
	- android.permission.WAKE_LOCK
	- android.permission.CAMERA
	- com.google.android.c2dm.permission.RECEIVE
	- eu.europa.ec.ecas.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION

**Comment by Exkaleburx** [comment]
Data *.* [0.9]
